<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AccountSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('accounts')->truncate();
        DB::table('accounts')->insert([

            /* =========================
             * COMPTE ÉPARGNE (4 produits)
             * ========================= */
            [
                'reference' => 'S002',
                'account_type' => 'Savings Account',
                'display_name' => 'Compte Épargne',
                'category' => 'individual',
                'currency' => 'USD',
                'interest_rate' => '2% par an',
                'initial_deposit' => '5 USD',
                'maintenance_fee' => '0 USD',
                'statement_fee' => '5 USD',
                'deposit_rule' => 'Illimité',
                'withdrawal_rule' => '1 retrait gratuit par mois',
                'withdrawal_fee' => '0,5% du montant retiré',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'S002-ENT',
                'account_type' => 'Savings Account',
                'display_name' => 'Compte Épargne',
                'category' => 'business',
                'currency' => 'USD',
                'interest_rate' => '2% par an',
                'initial_deposit' => '50 USD',
                'maintenance_fee' => '0 USD',
                'statement_fee' => '5 USD',
                'deposit_rule' => 'Illimité',
                'withdrawal_rule' => '1 retrait gratuit par mois',
                'withdrawal_fee' => '0,5% du montant retiré',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'S000',
                'account_type' => 'Savings Account',
                'display_name' => 'Compte Épargne',
                'category' => 'individual',
                'currency' => 'CDF',
                'interest_rate' => '2% par an',
                'initial_deposit' => '14 500 CDF',
                'maintenance_fee' => '0 CDF',
                'statement_fee' => '14 500 CDF',
                'deposit_rule' => 'Illimité',
                'withdrawal_rule' => '1 retrait gratuit par mois',
                'withdrawal_fee' => '0,5% du montant retiré',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'S000-ENT',
                'account_type' => 'Savings Account',
                'display_name' => 'Compte Épargne',
                'category' => 'business',
                'currency' => 'CDF',
                'interest_rate' => '2% par an',
                'initial_deposit' => '145 000 CDF',
                'maintenance_fee' => '0 CDF',
                'statement_fee' => '14 500 CDF',
                'deposit_rule' => 'Illimité',
                'withdrawal_rule' => '1 retrait gratuit par mois',
                'withdrawal_fee' => '0,5% du montant retiré',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            /* =========================
             * COMPTE COURANT (2 produits)
             * ========================= */
            [
                'reference' => 'C001',
                'account_type' => 'Current Account',
                'display_name' => 'Compte Courant',
                'category' => 'individual',
                'currency' => 'USD',
                'interest_rate' => 'Non rémunéré',
                'initial_deposit' => '10 USD',
                'maintenance_fee' => '5 USD / mois',
                'statement_fee' => '5 USD',
                'deposit_rule' => 'Libre',
                'withdrawal_rule' => 'Libre',
                'withdrawal_fee' => 'Selon grille IMF',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'C000',
                'account_type' => 'Current Account',
                'display_name' => 'Compte Courant',
                'category' => 'individual',
                'currency' => 'CDF',
                'interest_rate' => 'Non rémunéré',
                'initial_deposit' => '30 000 CDF',
                'maintenance_fee' => '15 000 CDF / mois',
                'statement_fee' => '14 500 CDF',
                'deposit_rule' => 'Libre',
                'withdrawal_rule' => 'Libre',
                'withdrawal_fee' => 'Selon grille IMF',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            /* =========================
             * COMPTE SALAIRE (2 produits)
             * ========================= */
            [
                'reference' => 'SAL01',
                'account_type' => 'Salary Account',
                'display_name' => 'Compte Salaire',
                'category' => 'individual',
                'currency' => 'USD',
                'interest_rate' => 'Non rémunéré',
                'initial_deposit' => '0',
                'maintenance_fee' => '0',
                'statement_fee' => '0',
                'deposit_rule' => 'Versement salaire',
                'withdrawal_rule' => 'Libre',
                'withdrawal_fee' => '0',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'SAL00',
                'account_type' => 'Salary Account',
                'display_name' => 'Compte Salaire',
                'category' => 'individual',
                'currency' => 'CDF',
                'interest_rate' => 'Non rémunéré',
                'initial_deposit' => '0',
                'maintenance_fee' => '0',
                'statement_fee' => '0',
                'deposit_rule' => 'Versement salaire',
                'withdrawal_rule' => 'Libre',
                'withdrawal_fee' => '0',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            /* =========================
             * COMPTE COLLECTIF (2 produits)
             * ========================= */
            [
                'reference' => 'COL00',
                'account_type' => 'Collective Account',
                'display_name' => 'Compte Collectif',
                'category' => 'group',
                'currency' => 'CDF',
                'interest_rate' => 'Selon accord',
                'initial_deposit' => '50 000 CDF',
                'maintenance_fee' => 'Variable',
                'statement_fee' => 'Variable',
                'deposit_rule' => 'Selon règlement du groupe',
                'withdrawal_rule' => 'Signature conjointe',
                'withdrawal_fee' => 'Selon grille IMF',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'COL01',
                'account_type' => 'Collective Account',
                'display_name' => 'Compte Collectif',
                'category' => 'group',
                'currency' => 'USD',
                'interest_rate' => 'Selon accord',
                'initial_deposit' => '100 USD',
                'maintenance_fee' => 'Variable',
                'statement_fee' => 'Variable',
                'deposit_rule' => 'Selon règlement du groupe',
                'withdrawal_rule' => 'Signature conjointe',
                'withdrawal_fee' => 'Selon grille IMF',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            /* =========================
             * DÉPÔT À TERME (3 produits)
             * ========================= */
            [
                'reference' => 'DAT01',
                'account_type' => 'Fixed Deposit',
                'display_name' => 'Dépôt à Terme',
                'category' => 'individual',
                'currency' => 'USD',
                'interest_rate' => 'Selon durée',
                'initial_deposit' => '100 USD',
                'maintenance_fee' => '0',
                'statement_fee' => '5 USD',
                'deposit_rule' => 'Dépôt unique',
                'withdrawal_rule' => 'À échéance',
                'withdrawal_fee' => 'Pénalité si retrait anticipé',
                'duration' => '3 mois',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'DAT02',
                'account_type' => 'Fixed Deposit',
                'display_name' => 'Dépôt à Terme',
                'category' => 'individual',
                'currency' => 'USD',
                'interest_rate' => 'Selon durée',
                'initial_deposit' => '100 USD',
                'maintenance_fee' => '0',
                'statement_fee' => '5 USD',
                'deposit_rule' => 'Dépôt unique',
                'withdrawal_rule' => 'À échéance',
                'withdrawal_fee' => 'Pénalité si retrait anticipé',
                'duration' => '6 mois',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'DAT03',
                'account_type' => 'Fixed Deposit',
                'display_name' => 'Dépôt à Terme',
                'category' => 'individual',
                'currency' => 'USD',
                'interest_rate' => 'Selon durée',
                'initial_deposit' => '100 USD',
                'maintenance_fee' => '0',
                'statement_fee' => '5 USD',
                'deposit_rule' => 'Dépôt unique',
                'withdrawal_rule' => 'À échéance',
                'withdrawal_fee' => 'Pénalité si retrait anticipé',
                'duration' => '12 mois',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'C001-ENT',
                'account_type' => 'Current Account',
                'display_name' => 'Compte Courant',
                'category' => 'business',
                'currency' => 'USD',
                'interest_rate' => 'Non rémunéré',
                'initial_deposit' => '100 USD',
                'maintenance_fee' => '10 USD / mois',
                'statement_fee' => '5 USD',
                'deposit_rule' => 'Libre',
                'withdrawal_rule' => 'Libre',
                'withdrawal_fee' => 'Selon grille IMF',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'reference' => 'C000-ENT',
                'account_type' => 'Current Account',
                'display_name' => 'Compte Courant',
                'category' => 'business',
                'currency' => 'CDF',
                'interest_rate' => 'Non rémunéré',
                'initial_deposit' => '250 000 CDF',
                'maintenance_fee' => '25 000 CDF / mois',
                'statement_fee' => '14 500 CDF',
                'deposit_rule' => 'Libre',
                'withdrawal_rule' => 'Libre',
                'withdrawal_fee' => 'Selon grille IMF',
                'duration' => '-',
                'min_age' => 18,
                'max_age' => null,
                'display_order' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
