<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CreditSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('credits')->insert([

            [
                'reference' => 'CRD_AGR',
                'name' => 'Agricultural Credit',
                'display_name' => 'Crédits AGR',
                'amount_range' => '100 USD à 80 000 USD',
                'duration_range' => '2 à 12 mois',
                'file_fee' => '2%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => '2,5% à 5,5% / mois',
                'penalty' => '1% par jour de retard',
                'repayment_mode' => 'Mensuel',
                'guarantee' => 'Garantie financière, parrainage, hypothèque',
                'display_order' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_SAL',
                'name' => 'Salary Credit',
                'display_name' => 'Crédits salaires',
                'amount_range' => '100 USD à 10 000 USD',
                'duration_range' => '2 à 24 mois',
                'file_fee' => '2%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => '2,5% / mois',
                'penalty' => '1% sur le remboursement manqué',
                'repayment_mode' => 'Mensuel',
                'guarantee' => 'Salaire, décompte final',
                'display_order' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_STAFF',
                'name' => 'Staff Credit',
                'display_name' => 'Crédits aux Personnels',
                'amount_range' => '100 USD à 15 000 USD',
                'duration_range' => '2 à 24 mois',
                'file_fee' => '0,5%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => '1% / mois',
                'penalty' => '1% sur le remboursement manqué',
                'repayment_mode' => 'Mensuel',
                'guarantee' => 'Salaire, décompte final',
                'display_order' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_ADV_SAL',
                'name' => 'Salary Advance',
                'display_name' => 'Avance sur salaire',
                'amount_range' => '1/3 du salaire',
                'duration_range' => '1 mois',
                'file_fee' => '0',
                'disbursement_fee' => '0',
                'interest_rate' => '5%',
                'penalty' => '1% sur le remboursement manqué',
                'repayment_mode' => 'Mensuel',
                'guarantee' => 'Salaire',
                'display_order' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_DARE',
                'name' => 'Short Term Credit',
                'display_name' => 'Crédit dare dare',
                'amount_range' => '100 USD à 10 000 USD',
                'duration_range' => '1 à 4 semaines',
                'file_fee' => '0,25%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => '2% / semaine',
                'penalty' => '1% sur le remboursement manqué',
                'repayment_mode' => 'Hebdomadaire',
                'guarantee' => 'Garantie financière',
                'display_order' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_PEPSI',
                'name' => 'Partner Credit',
                'display_name' => 'Credit PEPSI',
                'amount_range' => 'Selon convention',
                'duration_range' => 'Selon convention',
                'file_fee' => '0',
                'disbursement_fee' => '0',
                'interest_rate' => 'Selon convention',
                'penalty' => 'Selon convention',
                'repayment_mode' => 'Selon convention',
                'guarantee' => 'Convention partenaire',
                'display_order' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_AUTO',
                'name' => 'Auto Credit',
                'display_name' => 'Crédit Auto',
                'amount_range' => 'Selon valeur du véhicule',
                'duration_range' => '6 à 36 mois',
                'file_fee' => '2%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => '2% / mois',
                'penalty' => '1% sur le remboursement manqué',
                'repayment_mode' => 'Mensuel',
                'guarantee' => 'Véhicule',
                'display_order' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_GROUP',
                'name' => 'Group Credit',
                'display_name' => 'Crédit compte collectif',
                'amount_range' => 'Selon groupe',
                'duration_range' => '3 à 24 mois',
                'file_fee' => '1%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => '2% / mois',
                'penalty' => '1% sur le remboursement manqué',
                'repayment_mode' => 'Mensuel',
                'guarantee' => 'Garantie collective',
                'display_order' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_OD',
                'name' => 'Overdraft',
                'display_name' => 'Découvert Bancaire',
                'amount_range' => 'Selon compte',
                'duration_range' => 'Court terme',
                'file_fee' => '0',
                'disbursement_fee' => '0',
                'interest_rate' => '5% / mois',
                'penalty' => '1% par jour',
                'repayment_mode' => 'Automatique',
                'guarantee' => 'Compte',
                'display_order' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_LIKELEMBA',
                'name' => 'Likelemba Credit',
                'display_name' => 'Crédit LIKELEMBA',
                'amount_range' => 'Selon tontine',
                'duration_range' => 'Selon cycle',
                'file_fee' => '1%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => 'Selon accord',
                'penalty' => '1%',
                'repayment_mode' => 'Selon groupe',
                'guarantee' => 'Tontine',
                'display_order' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_MOTO',
                'name' => 'Motorcycle Credit',
                'display_name' => 'Crédit MOTO',
                'amount_range' => 'Selon valeur moto',
                'duration_range' => '6 à 24 mois',
                'file_fee' => '2%',
                'disbursement_fee' => '0,5%',
                'interest_rate' => '2% / mois',
                'penalty' => '1%',
                'repayment_mode' => 'Mensuel',
                'guarantee' => 'Moto',
                'display_order' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'reference' => 'CRD_PAECELLE',
                'name' => 'Parcel Credit',
                'display_name' => 'Crédit Paecelle - SOMBELA NZAMBE LOPANGO',
                'amount_range' => 'Selon projet',
                'duration_range' => 'Selon convention',
                'file_fee' => 'Selon convention',
                'disbursement_fee' => 'Selon convention',
                'interest_rate' => 'Selon convention',
                'penalty' => 'Selon convention',
                'repayment_mode' => 'Selon convention',
                'guarantee' => 'Titre foncier / parcelle',
                'display_order' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
